name: FairFare
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pre-commit
    - pytest
    - numpy
    - pandas
    - scikit-learn
    - black
    - isort
    - flake8
